name = "Tinkerer's Quilt Modded (1.19)"
author = "Sisby folk"
version = "4.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "190efbaab796e130909b39a4ae2979f5db0338ffbc1b197f31bb181d4da4d8bd"

[versions]
minecraft = "1.19.2"
quilt = "0.19.1"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
datapack-folder = "/resources/packs/"
