name = "Tinkerer's Quilt Modded (1.20)"
author = "Sisby folk"
version = "4.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a74c04f63fda30742761c4a97e5f9a4fb8a05b6796a41bdc01eb304f9c9168e2"

[versions]
minecraft = "1.20.1"
quilt = "0.29.2-beta.4"
unsup = "1.2.0-pre3"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
datapack-folder = "/resources/datapacks/"
resourcepack-folder = "/resources/resourcepacks/"
