name = "Tinkerer's Quilt Modded (1.20)"
author = "Sisby folk"
version = "4.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9290bdde7a0edc885de9f3ba147c90023b345afb31e0334d6f0b277aa18d8086"

[versions]
minecraft = "1.20.1"
quilt = "0.29.0-beta.7"
unsup = "1.1.3"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
datapack-folder = "/resources/datapacks/"
resourcepack-folder = "/resources/resourcepacks/"
