name = "Tinkerer's Quilt Modded (1.19)"
author = "Sisby folk"
version = "4.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "592a863b83d942e8ec058da4ae22783e96ba71bc2cb127a4cfe197f511057b2e"

[versions]
minecraft = "1.19.2"
quilt = "0.19.1"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
datapack-folder = "/resources/packs/"
