name = "Tinkerer's Quilt Modded (1.19)"
author = "Sisby Folk"
version = "3.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f5454a671fe5c2a143583cd2e37bf720f8d84d70308981189b9b0ac212922171"

[versions]
minecraft = "1.19.2"
quilt = "0.17.7"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
