name = "Tinkerer's Quilt Plus (1.19)"
author = "Sisby folk"
version = "4.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3297ab766ae4b2a5fbacf6136fb0e33ed5a1c66ed969edfd7ecbf9c7d4b3ead7"

[versions]
minecraft = "1.19.2"
quilt = "0.19.1"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
datapack-folder = "/resources/packs/"
