name = "Tinkerer's Quilt Modded (1.19)"
author = "Sisby folk"
version = "4.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5616469fbe8610dd9409215668329a295f92828c3a54c72c35fcc191329dc38d"

[versions]
minecraft = "1.19.2"
quilt = "0.19.1"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
datapack-folder = "/resources/packs/"
