#!/bin/sh

. git-sh-setup
echo "Refreshing Packwiz Index"
packwiz refresh
if ! git diff --quiet index.toml pack.toml; then
    echo "Difference found, amending"
    git add index.toml
    git add pack.toml
    rm "$GIT_DIR/MERGE_HEAD"
    git commit --amend --no-edit
fi
