placeSnowInBlock = false
snowGravity = true
snowAlwaysReplaceable = true
snowAccumulationDuringSnowstorm = true
snowAccumulationDuringSnowfall = false
snowAccumulationMaxLayers = 8
thinnerBoundingBox = true
snowMakingIce = true
snowOnIce = false
snowNeverMelt = false
snowMeltsInWarmBiomes = false
snowNaturalMelt = true
snowReduceFallDamage = true
replaceWorldFeature = false
sustainGrassIfLayerMoreThanOne = true
retainOriginalBlocks = true
sneakSnowball = false
mobSpawningMaxLayers = 8
